### ISSUE TITLE
Erroneous dataset image

### ISSUE THREAD

**Issue by cervonwong** [RenoirTan/beebeesee-2021#6]
![](https://raw.githubusercontent.com/RenoirTan/beebeesee-2021/main/train/angry/Training_10131352.jpg)
https://github.com/RenoirTan/beebeesee-2021/blob/main/train/angry/Training_10131352.jpg

angry

**Comment by ThePyProgrammer** [comment]
That's just how it was in the dataset, I mean I don't know what I can do... unless I go through every one of 30000 files, but thanks for asking.
